import PDFDocument from "pdfkit";
import type { SeoAuditReportRow } from "../db/reports.js";

interface SeoCheckItem {
  id: string;
  label: string;
  status: "pass" | "warn" | "fail";
  message: string;
}

export function generateReportPdf(report: SeoAuditReportRow): PDFKit.PDFDocument {
  const doc = new PDFDocument({ margin: 50, size: "A4" });
  const checks: SeoCheckItem[] = JSON.parse(report.checks_json);

  doc.fontSize(20).fillColor("#111111").text("SEO Audit Report", { align: "left" });
  doc.moveDown(0.3);
  doc.fontSize(10).fillColor("#666666").text(`Generated: ${new Date().toLocaleString()}`);
  doc.moveDown(1);

  doc.fontSize(12).fillColor("#111111").text("URL: ", { continued: true }).fillColor("#2563eb").text(report.url);
  doc.fillColor("#111111").fontSize(12).text(`Audit Date: ${report.created_at}`);
  doc.moveDown(0.5);

  doc.fontSize(16).fillColor("#111111").text(`Score: ${report.score}/100`);
  doc.moveDown(1);

  doc.fontSize(14).fillColor("#111111").text("Check Results", { underline: true });
  doc.moveDown(0.5);

  const statusColors: Record<string, string> = {
    pass: "#16a34a",
    warn: "#d97706",
    fail: "#dc2626",
  };

  for (const check of checks) {
    const color = statusColors[check.status] ?? "#111111";
    doc.fontSize(11).fillColor(color).text(`[${check.status.toUpperCase()}] `, { continued: true });
    doc.fillColor("#111111").text(check.label);
    doc.fontSize(9).fillColor("#555555").text(check.message, { indent: 15 });
    doc.moveDown(0.4);
  }

  doc.moveDown(1);
  doc.fontSize(14).fillColor("#111111").text("Recommendation", { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor("#333333").text(report.recommendation, { align: "left" });

  doc.moveDown(1.5);
  doc.fontSize(8).fillColor("#999999").text("Generated by AI Growth OS", { align: "center" });

  return doc;
}
